# Site settings
title: "Beegit - Content Production and Collaboration Blog"
email: "mike@beegit.com"
description: "The 'must read' blog for content managers. Let Beegit help you master the content production process."
baseurl: ""
url: "http://blog.beegit.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
permalink: pretty

gems:
 - jekyll-redirect-from
 - jekyll-redirect-to
